version: '2.0'
services:
  springboot:
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb
    container_name: workshop_api
    ports: 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-network
  mongo:
    image: mongo
    container_name: workshop_mongodb
    ports:
      - 27017:27017
    networks:
      - spring-mongo-network

networks:
  spring-mongo-network:
    driver: bridge